use crate::{PerGearSlot, SlotInfo, PerQuality, Prefix, PerStat, StatFormula};

// BEGIN GENERATED CODE
// Generated by gen_gear_tables.py for GW2 build 142239 at 2023-03-05T18:00:01

pub static GEAR_SLOTS: PerGearSlot<SlotInfo> = PerGearSlot {
    weapon_1h: SlotInfo {
        points: PerQuality {
            exotic: 341.44,
            ascended: 358.512,
        },
        add_base: false,
    },
    weapon_2h: SlotInfo {
        points: PerQuality {
            exotic: 682.88,
            ascended: 717.024,
        },
        add_base: false,
    },
    helm: SlotInfo {
        points: PerQuality {
            exotic: 170.72,
            ascended: 179.256,
        },
        add_base: false,
    },
    shoulders: SlotInfo {
        points: PerQuality {
            exotic: 128.04,
            ascended: 134.442,
        },
        add_base: false,
    },
    coat: SlotInfo {
        points: PerQuality {
            exotic: 384.12,
            ascended: 403.326,
        },
        add_base: false,
    },
    gloves: SlotInfo {
        points: PerQuality {
            exotic: 128.04,
            ascended: 134.442,
        },
        add_base: false,
    },
    leggings: SlotInfo {
        points: PerQuality {
            exotic: 256.08,
            ascended: 268.884,
        },
        add_base: false,
    },
    boots: SlotInfo {
        points: PerQuality {
            exotic: 128.04,
            ascended: 134.442,
        },
        add_base: false,
    },
    amulet: SlotInfo {
        points: PerQuality {
            exotic: 341.44,
            ascended: 358.512,
        },
        add_base: true,
    },
    ring1: SlotInfo {
        points: PerQuality {
            exotic: 256.08,
            ascended: 268.884,
        },
        add_base: true,
    },
    ring2: SlotInfo {
        points: PerQuality {
            exotic: 256.08,
            ascended: 268.884,
        },
        add_base: true,
    },
    accessory1: SlotInfo {
        points: PerQuality {
            exotic: 213.4,
            ascended: 224.07,
        },
        add_base: true,
    },
    accessory2: SlotInfo {
        points: PerQuality {
            exotic: 213.4,
            ascended: 224.07,
        },
        add_base: true,
    },
    backpack: SlotInfo {
        points: PerQuality {
            exotic: 85.36,
            ascended: 89.628,
        },
        add_base: true,
    },
};

pub const NUM_PREFIXES: usize = 38;

pub static PREFIXES: [Prefix; NUM_PREFIXES] = [
    Prefix {
        name: "Apothecary's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Assassin's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Berserker's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Bringer's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Carrion",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Cavalier's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Celestial",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            condition_damage: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            expertise: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 0.0,
                    ascended: 13.0,
                },
            },
            vitality: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            toughness: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 12.0,
                    ascended: 13.0,
                },
            },
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 0.0,
                    ascended: 13.0,
                },
            },
        },
    },
    Prefix {
        name: "Cleric's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Commander's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Crusader",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Dire",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Diviner's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
        },
    },
    Prefix {
        name: "Dragon's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Giver's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
        },
    },
    Prefix {
        name: "Grieving",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Harrier's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
        },
    },
    Prefix {
        name: "Knight's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Magi's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Marauder",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            ferocity: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Marshal's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Minstrel's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            toughness: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Nomad's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Plaguedoctor's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Rabid",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Rampager's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Ritualist's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            vitality: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Sentinel's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Seraph",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Settler's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Shaman's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Sinister",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Soldier's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Trailblazer's",
        formulas: PerStat {
            power: StatFormula::ZERO,
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            vitality: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            toughness: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Valkyrie",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Vigilant",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            vitality: StatFormula::ZERO,
            toughness: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Viper's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            expertise: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula::ZERO,
            concentration: StatFormula::ZERO,
        },
    },
    Prefix {
        name: "Wanderer's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            precision: StatFormula::ZERO,
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula {
                factor: 0.3,
                base: PerQuality {
                    exotic: 20.0,
                    ascended: 25.0,
                },
            },
            toughness: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
            healing_power: StatFormula::ZERO,
            concentration: StatFormula {
                factor: 0.165,
                base: PerQuality {
                    exotic: 10.0,
                    ascended: 12.0,
                },
            },
        },
    },
    Prefix {
        name: "Zealot's",
        formulas: PerStat {
            power: StatFormula {
                factor: 0.35,
                base: PerQuality {
                    exotic: 25.0,
                    ascended: 32.0,
                },
            },
            precision: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            ferocity: StatFormula::ZERO,
            condition_damage: StatFormula::ZERO,
            expertise: StatFormula::ZERO,
            vitality: StatFormula::ZERO,
            toughness: StatFormula::ZERO,
            healing_power: StatFormula {
                factor: 0.25,
                base: PerQuality {
                    exotic: 15.0,
                    ascended: 18.0,
                },
            },
            concentration: StatFormula::ZERO,
        },
    },
];

// END GENERATED CODE
