use crate::effect::Effect;
use crate::stats::{Stats, Modifiers};

// BEGIN GENERATED CODE
// Generated by gen_gear_tables.py for GW2 build 142239 at 2023-03-06T03:41:56

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Altruism;
#[allow(unused_variables)]
impl Effect for Altruism {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration += 5.0;
        s.healing_power += 50.0;
        m.boon_duration += 10.0;
        s.healing_power += 100.0;
        s.healing_power += 125.0;
        // unknown effect: 'transfer 1 condition from 5 allies within a 600 radius to yourself after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Antitoxin;
#[allow(unused_variables)]
impl Effect for Antitoxin {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        // -5.0 incoming condition duration
        s.condition_damage += 50.0;
        // -10.0 incoming condition duration
        s.condition_damage += 100.0;
        // -10.0 incoming condition duration
        // unknown effect: 'incoming condition cleanses remove an additional condition'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Balthazar;
#[allow(unused_variables)]
impl Effect for Balthazar {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.burn += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.burn += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration.burn += 20.0;
        m.max_health += 10.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Divinity;
#[allow(unused_variables)]
impl Effect for Divinity {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        *s += 10.0;
        *s += 12.0;
        *s += 14.0;
        *s += 16.0;
        // unknown effect: '+18 to all stats, +10% maximum health'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Durability;
#[allow(unused_variables)]
impl Effect for Durability {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        m.boon_duration += 5.0;
        s.toughness += 50.0;
        m.boon_duration += 10.0;
        s.toughness += 100.0;
        m.max_health += 10.0;
        // unknown effect: 'grant nearby allies protection and regeneration for 3 seconds, and resistance for 1 second when struck'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Dwayna;
#[allow(unused_variables)]
impl Effect for Dwayna {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration.regeneration += 10.0;
        s.healing_power += 50.0;
        m.boon_duration.regeneration += 20.0;
        s.healing_power += 100.0;
        m.max_health += 10.0;
        // unknown effect: 'regeneration you apply is 20% more effective'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Evasion;
#[allow(unused_variables)]
impl Effect for Evasion {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += 25.0;
        m.boon_duration.swiftness += 10.0;
        s.ferocity += 50.0;
        m.boon_duration.swiftness += 20.0;
        s.ferocity += 100.0;
        s.ferocity += 125.0;
        // unknown effect: 'gain swiftness for 6 seconds after evading an attack'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Exuberance;
#[allow(unused_variables)]
impl Effect for Exuberance {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        s.vitality += 50.0;
        s.vitality += 100.0;
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += s.vitality * 0.03;
        s.precision += s.vitality * 0.05;
        s.power += s.vitality * 0.07;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Fireworks;
#[allow(unused_variables)]
impl Effect for Fireworks {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration += 5.0;
        s.power += 50.0;
        m.boon_duration += 10.0;
        s.power += 100.0;
        // +25.0 movement speed
        // unknown effect: 'gain 6 stacks of might, fury, and vigor for 6 seconds while in combat. (cooldown: 20 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Grenth;
#[allow(unused_variables)]
impl Effect for Grenth {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        //m.condition_duration.<chill> += 10.0;
        s.condition_damage += 50.0;
        //m.condition_duration.<chill> += 20.0;
        s.condition_damage += 100.0;
        //m.condition_duration.<chill> += 20.0;
        // unknown effect: 'chill nearby foes after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Hoelbrak;
#[allow(unused_variables)]
impl Effect for Hoelbrak {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.might += 10.0;
        s.power += 50.0;
        // -10.0 incoming condition duration
        s.power += 100.0;
        m.boon_duration += 10.0;
        // -10.0 incoming condition damage
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Infiltration;
#[allow(unused_variables)]
impl Effect for Infiltration {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.precision += 35.0;
        s.power += 50.0;
        s.precision += 65.0;
        s.power += 100.0;
        // unknown effect: 'deal +10% increased strike damage to enemies below 50% health'
        // unknown effect: 'gain 5 seconds of vigor after entering stealth. (cooldown: 30 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Leadership;
#[allow(unused_variables)]
impl Effect for Leadership {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        m.boon_duration += 5.0;
        *s += 12.0;
        m.boon_duration += 10.0;
        *s += 16.0;
        m.boon_duration += 10.0;
        // unknown effect: 'convert up to 3 conditions into boons for nearby allies after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Lyssa;
#[allow(unused_variables)]
impl Effect for Lyssa {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.precision += 25.0;
        m.condition_duration += 5.0;
        s.precision += 50.0;
        m.boon_duration += 10.0;
        s.precision += 100.0;
        m.condition_duration += 10.0;
        // unknown effect: 'convert up to 3 conditions into boons after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Melandru;
#[allow(unused_variables)]
impl Effect for Melandru {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.vitality += 35.0;
        s.toughness += 50.0;
        // -10.0 incoming condition duration
        s.toughness += 100.0;
        // -10.0 incoming condition duration
        // -20.0 incoming stun duration
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Mercy;
#[allow(unused_variables)]
impl Effect for Mercy {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.healing_power += 35.0;
        s.toughness += 50.0;
        // unknown effect: '-20% incoming damage while reviving an ally'
        s.toughness += 100.0;
        // unknown effect: 'revive allies 20% faster and with 30% more health'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct NaturesBounty;
#[allow(unused_variables)]
impl Effect for NaturesBounty {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        // -5.0 incoming condition duration
        s.healing_power += 50.0;
        // -10.0 incoming condition duration
        s.healing_power += 100.0;
        // -10.0 incoming condition duration
        // unknown effect: 'cleanse a condition from nearby allies after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Orr;
#[allow(unused_variables)]
impl Effect for Orr {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        // -5.0 incoming condition duration
        s.condition_damage += 50.0;
        // -10.0 incoming condition duration
        s.condition_damage += 100.0;
        // -10.0 incoming condition duration
        m.max_health += 10.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Perplexity;
#[allow(unused_variables)]
impl Effect for Perplexity {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.confuse += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.confuse += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration.confuse += 20.0;
        // unknown effect: 'decrease strike damage dealt to you by confused foes by 10%'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Radiance;
#[allow(unused_variables)]
impl Effect for Radiance {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        m.boon_duration += 5.0;
        s.vitality += 50.0;
        m.boon_duration += 10.0;
        s.vitality += 100.0;
        m.boon_duration += 10.0;
        // unknown effect: 'increase the duration of auras you grant by +33%'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Rage;
#[allow(unused_variables)]
impl Effect for Rage {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += 25.0;
        m.boon_duration.fury += 10.0;
        s.ferocity += 50.0;
        // unknown effect: 'gain fury for 8 seconds when entering combat. (cooldown: 10 seconds)'
        s.ferocity += 100.0;
        m.boon_duration.fury += 20.0;
        // unknown effect: 'increase strike damage dealt by 5% while under the effect of fury'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct RataSum;
#[allow(unused_variables)]
impl Effect for RataSum {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.precision += 25.0;
        m.condition_duration.poison += 10.0;
        s.precision += 50.0;
        //m.condition_duration.<weakness> += 20.0;
        s.precision += 100.0;
        m.condition_duration += 10.0;
        // unknown effect: 'summon a gamma-ray field that grants might upon entering combat'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Resistance;
#[allow(unused_variables)]
impl Effect for Resistance {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        // -5.0 incoming condition duration
        s.toughness += 50.0;
        // -10.0 incoming condition duration
        s.toughness += 100.0;
        // -10.0 incoming condition duration
        // unknown effect: 'gain resistance for 4 seconds after activating an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Sanctuary;
#[allow(unused_variables)]
impl Effect for Sanctuary {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        m.boon_duration += 5.0;
        s.vitality += 50.0;
        m.boon_duration += 10.0;
        s.vitality += 100.0;
        // unknown effect: 'gain a barrier with health equal to 10% of any healing you receive'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Scavenging;
#[allow(unused_variables)]
impl Effect for Scavenging {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.vitality += 35.0;
        s.condition_damage += 50.0;
        s.vitality += 65.0;
        s.condition_damage += 100.0;
        m.condition_duration.poison += 20.0;
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += s.vitality * 0.07;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Snowfall;
#[allow(unused_variables)]
impl Effect for Snowfall {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        // unknown effect: 'gain 15 seconds of regeneration when you take falling damage'
        s.toughness += 50.0;
        // unknown effect: 'gain 3 seconds of superspeed when you take falling damage'
        s.toughness += 100.0;
        // unknown effect: 'create a pile of snow that chills enemies when you take falling damage'
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += s.toughness * 0.05;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Speed;
#[allow(unused_variables)]
impl Effect for Speed {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        m.boon_duration.swiftness += 10.0;
        s.vitality += 50.0;
        m.boon_duration.swiftness += 20.0;
        s.vitality += 100.0;
        m.boon_duration.swiftness += 20.0;
        // unknown effect: 'increase movement speed by 66% when under the effect of swiftness'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Strength;
#[allow(unused_variables)]
impl Effect for Strength {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.might += 10.0;
        s.power += 50.0;
        m.boon_duration.might += 20.0;
        s.power += 100.0;
        m.boon_duration.might += 20.0;
        // unknown effect: 'increase strike damage by 5% while under the effect of might'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Surging;
#[allow(unused_variables)]
impl Effect for Surging {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration += 5.0;
        s.power += 50.0;
        m.boon_duration += 10.0;
        s.power += 100.0;
        // +25.0 movement speed
        // unknown effect: 'gain shocking aura for 4 seconds after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Svanir;
#[allow(unused_variables)]
impl Effect for Svanir {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        //m.condition_duration.<chill> += 10.0;
        s.toughness += 50.0;
        //m.condition_duration.<chill> += 20.0;
        s.toughness += 100.0;
        // -66.0 incoming chill duration
        // unknown effect: 'gain frost aura for 4 seconds when hit by a foe while under 50% health'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Thorns;
#[allow(unused_variables)]
impl Effect for Thorns {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.poison += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.poison += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration.poison += 20.0;
        s.condition_damage += 125.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Tormenting;
#[allow(unused_variables)]
impl Effect for Tormenting {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.torment += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.torment += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration.torment += 20.0;
        // unknown effect: 'gain regeneration for 3 seconds after inflicting a foe with torment. (cooldown: 5 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Vampirism;
#[allow(unused_variables)]
impl Effect for Vampirism {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.vitality += 35.0;
        s.power += 50.0;
        s.vitality += 65.0;
        s.power += 100.0;
        m.max_health += 10.0;
        // unknown effect: 'restore 10% of your health upon killing a foe'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Adventurer;
#[allow(unused_variables)]
impl Effect for Adventurer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.power += 35.0;
        s.condition_damage += 50.0;
        s.power += 65.0;
        s.condition_damage += 100.0;
        s.power += 125.0;
        // unknown effect: 'gain 50% endurance after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Afflicted;
#[allow(unused_variables)]
impl Effect for Afflicted {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.poison += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.bleed += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration += 10.0;
        // unknown effect: "create a death nova at a foe's location upon their defeat. (cooldown: 15 seconds)"
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Air;
#[allow(unused_variables)]
impl Effect for Air {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += 25.0;
        m.boon_duration.swiftness += 10.0;
        s.ferocity += 50.0;
        m.boon_duration.swiftness += 20.0;
        s.ferocity += 100.0;
        m.boon_duration.swiftness += 20.0;
        // unknown effect: 'gain shocking aura for 4 seconds after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Aristocracy;
#[allow(unused_variables)]
impl Effect for Aristocracy {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.boon_duration.might += 10.0;
        s.condition_damage += 50.0;
        m.boon_duration.might += 20.0;
        s.condition_damage += 100.0;
        m.boon_duration.might += 20.0;
        // unknown effect: 'gain 5 stacks of might for 4 seconds after inflicting weakness on a foe. (cooldown: 1 second)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Baelfire;
#[allow(unused_variables)]
impl Effect for Baelfire {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.condition_duration.burn += 10.0;
        s.power += 50.0;
        m.condition_duration += 10.0;
        s.power += 100.0;
        m.condition_duration.burn += 20.0;
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.expertise += s.power * 0.07;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Berserker;
#[allow(unused_variables)]
impl Effect for Berserker {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.power += 35.0;
        s.condition_damage += 50.0;
        s.power += 65.0;
        s.condition_damage += 100.0;
        m.strike_damage += 5.0; m.condition_damage += 5.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Brawler;
#[allow(unused_variables)]
impl Effect for Brawler {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.toughness += 35.0;
        s.power += 50.0;
        s.toughness += 65.0;
        s.power += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'gain 5 stacks of might for 10 seconds after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Cavalier;
#[allow(unused_variables)]
impl Effect for Cavalier {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.toughness += 35.0;
        s.power += 50.0;
        s.toughness += 65.0;
        s.power += 100.0;
        // unknown effect: 'using an <c=@abilitytype>engage</c> ability grants quickness and bonus damage for 5 seconds'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Centaur;
#[allow(unused_variables)]
impl Effect for Centaur {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.swiftness += 10.0;
        s.power += 50.0;
        m.boon_duration.swiftness += 20.0;
        s.power += 100.0;
        m.boon_duration.swiftness += 20.0;
        // unknown effect: 'grant swiftness to nearby allies for 10 seconds after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Chronomancer;
#[allow(unused_variables)]
impl Effect for Chronomancer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.precision += 35.0;
        s.power += 50.0;
        s.precision += 65.0;
        s.power += 100.0;
        // unknown effect: 'apply 2 seconds of quickness when you cast a well'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Citadel;
#[allow(unused_variables)]
impl Effect for Citadel {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.fury += 10.0;
        s.power += 50.0;
        m.boon_duration.fury += 20.0;
        s.power += 100.0;
        m.boon_duration.fury += 20.0;
        // unknown effect: 'call in an artillery strike at your position after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Daredevil;
#[allow(unused_variables)]
impl Effect for Daredevil {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.toughness += 35.0;
        s.power += 50.0;
        s.toughness += 65.0;
        s.power += 100.0;
        // unknown effect: 'next attack is guaranteed to crit after completing a dodge roll while in combat'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Deadeye;
#[allow(unused_variables)]
impl Effect for Deadeye {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.ferocity += 35.0;
        s.power += 50.0;
        s.ferocity += 65.0;
        s.power += 100.0;
        // unknown effect: 'apply 2 stacks of might for 15 seconds when you use a cantrip'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Defender;
#[allow(unused_variables)]
impl Effect for Defender {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.healing_power += 35.0;
        s.toughness += 50.0;
        s.healing_power += 65.0;
        s.toughness += 100.0;
        m.max_health += 10.0;
        // unknown effect: 'heal for 5% of your maximum health after blocking an attack. (cooldown: 1 second)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Dolyak;
#[allow(unused_variables)]
impl Effect for Dolyak {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.vitality += 35.0;
        s.toughness += 50.0;
        s.vitality += 65.0;
        s.toughness += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'regenerate health every second'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Dragonhunter;
#[allow(unused_variables)]
impl Effect for Dragonhunter {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += 25.0;
        s.power += 35.0;
        s.ferocity += 50.0;
        s.power += 65.0;
        s.ferocity += 100.0;
        // unknown effect: 'apply 5 stacks of might for 8 seconds when you place a trap'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Druid;
#[allow(unused_variables)]
impl Effect for Druid {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        s.vitality += 35.0;
        s.healing_power += 50.0;
        s.vitality += 65.0;
        s.healing_power += 100.0;
        // unknown effect: 'gain +500 healing power for 3 seconds after casting a glyph'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Eagle;
#[allow(unused_variables)]
impl Effect for Eagle {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.precision += 25.0;
        s.ferocity += 35.0;
        s.precision += 50.0;
        s.ferocity += 65.0;
        s.precision += 100.0;
        s.ferocity += 125.0;
        // unknown effect: 'deal 10% increased strike damage to targets with less than 50% health'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Earth;
#[allow(unused_variables)]
impl Effect for Earth {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        m.boon_duration.protection += 10.0;
        s.toughness += 50.0;
        m.boon_duration.protection += 20.0;
        s.toughness += 100.0;
        // +10.0 incoming heal effectiveness
        // unknown effect: 'gain protection and magnetic aura when struck by a foe'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Elementalist;
#[allow(unused_variables)]
impl Effect for Elementalist {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.condition_damage += 35.0;
        s.power += 50.0;
        s.condition_damage += 65.0;
        s.power += 100.0;
        s.condition_damage += 125.0;
        m.condition_duration += 10.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Engineer;
#[allow(unused_variables)]
impl Effect for Engineer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.condition_damage += 35.0;
        s.toughness += 50.0;
        s.condition_damage += 65.0;
        s.toughness += 100.0;
        s.condition_damage += 125.0;
        // unknown effect: 'increase strike damage dealt by 7% while wielding conjured weapons, environmental weapons, kits, and banners'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Fire;
#[allow(unused_variables)]
impl Effect for Fire {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.might += 10.0;
        s.power += 50.0;
        // unknown effect: 'gain fire aura for 4 seconds when entering combat'
        s.power += 100.0;
        m.condition_duration.burn += 20.0;
        // unknown effect: 'increase strike damage by 10% while fire aura is active'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Firebrand;
#[allow(unused_variables)]
impl Effect for Firebrand {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.boon_duration.quickness += 10.0;
        s.condition_damage += 50.0;
        m.boon_duration += 10.0;
        s.condition_damage += 100.0;
        m.boon_duration.quickness += 20.0;
        // unknown effect: 'when you use an elite skill, inflict burning on nearby enemies'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct FlameLegion;
#[allow(unused_variables)]
impl Effect for FlameLegion {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.condition_duration.burn += 10.0;
        s.power += 50.0;
        m.condition_duration.burn += 20.0;
        s.power += 100.0;
        m.condition_duration.burn += 20.0;
        // unknown effect: 'increase damage to burning foes by 7%'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Flock;
#[allow(unused_variables)]
impl Effect for Flock {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        s.vitality += 35.0;
        s.healing_power += 50.0;
        s.vitality += 65.0;
        s.healing_power += 100.0;
        m.max_health += 10.0;
        // unknown effect: 'you and nearby allies are healed for an additional amount after you use a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Forgeman;
#[allow(unused_variables)]
impl Effect for Forgeman {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        m.condition_duration.burn += 10.0;
        s.toughness += 50.0;
        m.condition_duration.burn += 20.0;
        s.toughness += 100.0;
        m.condition_duration.burn += 20.0;
        // unknown effect: 'gain fire aura for 4 seconds when struck by a foe while below 75% health. (cooldown: 20 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Golemancer;
#[allow(unused_variables)]
impl Effect for Golemancer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += 25.0;
        s.precision += 35.0;
        s.ferocity += 50.0;
        s.precision += 65.0;
        s.ferocity += 100.0;
        s.ferocity += 125.0;
        // unknown effect: 'summon a golem while in combat'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Grove;
#[allow(unused_variables)]
impl Effect for Grove {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration.protection += 10.0;
        s.healing_power += 50.0;
        m.boon_duration.protection += 20.0;
        s.healing_power += 100.0;
        m.boon_duration.protection += 20.0;
        // unknown effect: 'when struck by a foe, a meadow blooms at your location, granting vigor, regeneration, and protection to allies within it'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Guardian;
#[allow(unused_variables)]
impl Effect for Guardian {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        s.healing_power += 35.0;
        s.toughness += 50.0;
        s.healing_power += 65.0;
        s.toughness += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'burn a foe for 1 second after blocking its attack'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Herald;
#[allow(unused_variables)]
impl Effect for Herald {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.toughness += 25.0;
        m.boon_duration += 5.0;
        s.toughness += 50.0;
        m.boon_duration += 10.0;
        s.toughness += 100.0;
        // unknown effect: 'when using a heal skill, apply protection to nearby allies (360 radius).<br>'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Holosmith;
#[allow(unused_variables)]
impl Effect for Holosmith {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.vitality += 35.0;
        s.power += 50.0;
        s.vitality += 65.0;
        s.power += 100.0;
        // unknown effect: 'gain a laser-disc when struck below the 75% health threshold'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Ice;
#[allow(unused_variables)]
impl Effect for Ice {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        //m.condition_duration.<chill> += 10.0;
        s.vitality += 50.0;
        //m.condition_duration.<chill> += 20.0;
        s.vitality += 100.0;
        // unknown effect: '+7% damage to chilled foes'
        // unknown effect: 'surround yourself with an ice nova after using an elite skill. (cooldown: 10 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Krait;
#[allow(unused_variables)]
impl Effect for Krait {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration.bleed += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration.bleed += 20.0;
        s.condition_damage += 100.0;
        m.condition_duration.bleed += 20.0;
        // unknown effect: 'inflict bleeding, torment, and poison to nearby foes for 8 seconds after using an elite skill '
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Lich;
#[allow(unused_variables)]
impl Effect for Lich {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        m.condition_duration += 5.0;
        s.vitality += 50.0;
        m.condition_duration += 10.0;
        s.vitality += 100.0;
        m.condition_damage += 4.0;
        // unknown effect: 'summon a jagged horror while in combat'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct MadKing;
#[allow(unused_variables)]
impl Effect for MadKing {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.condition_duration += 5.0;
        s.power += 50.0;
        m.condition_duration.bleed += 20.0;
        s.power += 100.0;
        m.condition_duration.bleed += 20.0;
        // unknown effect: 'summon ravens to attack nearby enemies after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Mesmer;
#[allow(unused_variables)]
impl Effect for Mesmer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.precision += 35.0;
        s.power += 50.0;
        s.precision += 65.0;
        s.power += 100.0;
        //m.condition_duration.<daze> += 33.0;
        // unknown effect: 'increase strike damage dealt to dazed foes by 10%'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Mirage;
#[allow(unused_variables)]
impl Effect for Mirage {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.toughness += 35.0;
        s.condition_damage += 50.0;
        s.toughness += 65.0;
        s.condition_damage += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'inflict torment for 4 seconds upon successfully evading an attack. (cooldown: 1 second)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Monk;
#[allow(unused_variables)]
impl Effect for Monk {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration += 5.0;
        s.healing_power += 50.0;
        m.boon_duration += 10.0;
        s.healing_power += 100.0;
        // unknown effect: '+10% healing effectiveness to other allies'
        // unknown effect: 'increase healing effectiveness to other allies by an additional 1% for 3 seconds after granting a boon to any ally (up to a maximum of 10 stacks)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Necromancer;
#[allow(unused_variables)]
impl Effect for Necromancer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.vitality += 35.0;
        s.condition_damage += 50.0;
        s.vitality += 65.0;
        s.condition_damage += 100.0;
        s.condition_damage += 125.0;
        // unknown effect: '20% fear duration'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Nightmare;
#[allow(unused_variables)]
impl Effect for Nightmare {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        //m.condition_duration.<fear> += 10.0;
        s.condition_damage += 50.0;
        m.condition_duration += 10.0;
        s.condition_damage += 100.0;
        m.condition_duration += 10.0;
        // unknown effect: 'deliver an attack that transfers a condition and blinds nearby enemies after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Ogre;
#[allow(unused_variables)]
impl Effect for Ogre {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.ferocity += 35.0;
        s.power += 50.0;
        s.ferocity += 65.0;
        s.power += 100.0;
        m.strike_damage += 4.0;
        // unknown effect: 'summon a rock dog while in combat'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Pack;
#[allow(unused_variables)]
impl Effect for Pack {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration += 5.0;
        s.power += 50.0;
        m.boon_duration += 10.0;
        s.power += 100.0;
        s.precision += 125.0;
        // unknown effect: 'grant nearby allies 5 stacks of might, fury, and swiftness for 8 seconds while in combat. (cooldown: 30 seconds)'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Privateer;
#[allow(unused_variables)]
impl Effect for Privateer {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        m.boon_duration.might += 10.0;
        s.power += 50.0;
        m.boon_duration.might += 20.0;
        s.power += 100.0;
        // unknown effect: 'shout "yarr!" while in combat, summoning a parrot and granting might to allies'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Ranger;
#[allow(unused_variables)]
impl Effect for Ranger {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.precision += 25.0;
        s.ferocity += 35.0;
        s.precision += 50.0;
        s.ferocity += 65.0;
        s.precision += 100.0;
        // unknown effect: '+7% damage while you have an active companion'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Reaper;
#[allow(unused_variables)]
impl Effect for Reaper {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.toughness += 35.0;
        s.power += 50.0;
        s.toughness += 65.0;
        s.power += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'chill enemies within a 360 radius for 1 second after executing a shout skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Rebirth;
#[allow(unused_variables)]
impl Effect for Rebirth {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration += 5.0;
        s.healing_power += 50.0;
        m.boon_duration += 10.0;
        s.healing_power += 100.0;
        s.healing_power += 125.0;
        // unknown effect: 'ignore the next lethal blow and gain barrier'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Renegade;
#[allow(unused_variables)]
impl Effect for Renegade {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.ferocity += 35.0;
        s.condition_damage += 50.0;
        s.ferocity += 65.0;
        s.condition_damage += 100.0;
        m.condition_damage += 7.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Revenant;
#[allow(unused_variables)]
impl Effect for Revenant {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        *s += 10.0;
        *s += 12.0;
        *s += 14.0;
        *s += 16.0;
        *s += 18.0;
        // unknown effect: 'gain 2 seconds of resistance after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Scholar;
#[allow(unused_variables)]
impl Effect for Scholar {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.ferocity += 35.0;
        s.power += 50.0;
        s.ferocity += 65.0;
        s.power += 100.0;
        s.ferocity += 125.0;
        // unknown effect: 'increase strike damage by 5% while your health is above 90%'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Scourge;
#[allow(unused_variables)]
impl Effect for Scourge {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        s.condition_damage += 35.0;
        s.healing_power += 50.0;
        s.condition_damage += 65.0;
        s.healing_power += 100.0;
        s.healing_power += 125.0;
        // unknown effect: 'gain barrier when struck by a foe while below 75% health'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Scrapper;
#[allow(unused_variables)]
impl Effect for Scrapper {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.toughness += 35.0;
        s.power += 50.0;
        s.toughness += 65.0;
        s.power += 100.0;
        // unknown effect: 'damage reduced by 7% when within 600 units of an enemy'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Soulbeast;
#[allow(unused_variables)]
impl Effect for Soulbeast {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.power += 35.0;
        s.condition_damage += 50.0;
        s.power += 65.0;
        s.condition_damage += 100.0;
        // unknown effect: 'when you have an active pet, gain condition damage equal to 7% of your power'
        // unknown effect: 'when you do not have an active pet, gain toughness equal to 7% of your condition damage'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Spellbreaker;
#[allow(unused_variables)]
impl Effect for Spellbreaker {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.power += 25.0;
        s.precision += 35.0;
        s.power += 50.0;
        s.precision += 65.0;
        s.power += 100.0;
        // unknown effect: 'you deal 7% more damage to foes that have no boons'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Stars;
#[allow(unused_variables)]
impl Effect for Stars {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        // -30.0 incoming weakness duration
        *s += 12.0;
        // unknown effect: '-30% incoming chill and cripple duration'
        *s += 16.0;
        // -10.0 incoming condition damage
        // -10.0 incoming condition duration
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Sunless;
#[allow(unused_variables)]
impl Effect for Sunless {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        // -5.0 incoming condition duration
        s.condition_damage += 50.0;
        // -10.0 incoming condition duration
        s.condition_damage += 100.0;
        // -10.0 incoming condition duration
        // unknown effect: 'inflict nearby foes with 1 second of fear and 5 seconds of poison after using an elite skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Tempest;
#[allow(unused_variables)]
impl Effect for Tempest {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        m.condition_duration += 5.0;
        *s += 12.0;
        m.condition_duration += 10.0;
        *s += 16.0;
        m.condition_duration += 10.0;
        // unknown effect: 'heal allies within a 360 radius after breaking a stun'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Thief;
#[allow(unused_variables)]
impl Effect for Thief {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.precision += 25.0;
        s.condition_damage += 35.0;
        s.precision += 50.0;
        s.condition_damage += 65.0;
        s.precision += 100.0;
        s.precision += 125.0;
        // unknown effect: 'increase strike damage dealt by 10% when striking a foe from behind or the flank'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Trapper;
#[allow(unused_variables)]
impl Effect for Trapper {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        m.condition_duration += 5.0;
        s.condition_damage += 50.0;
        m.condition_duration += 10.0;
        s.condition_damage += 100.0;
        // unknown effect: 'gain 3 seconds of stealth and superspeed after using a trap skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Traveler;
#[allow(unused_variables)]
impl Effect for Traveler {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        m.boon_duration += 5.0;
        *s += 12.0;
        m.boon_duration += 10.0;
        *s += 16.0;
        // +25.0 movement speed
        m.condition_duration += 10.0;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Trooper;
#[allow(unused_variables)]
impl Effect for Trooper {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        s.toughness += 35.0;
        s.vitality += 50.0;
        s.toughness += 65.0;
        s.vitality += 100.0;
        s.toughness += 125.0;
        // unknown effect: 'remove a condition from each affected ally after using a shout skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Undead;
#[allow(unused_variables)]
impl Effect for Undead {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += 25.0;
        s.toughness += 35.0;
        s.condition_damage += 50.0;
        s.toughness += 65.0;
        s.condition_damage += 100.0;
        s.toughness += 125.0;
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.condition_damage += s.toughness * 0.07;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Warrior;
#[allow(unused_variables)]
impl Effect for Warrior {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        s.power += 35.0;
        s.vitality += 50.0;
        s.power += 65.0;
        s.vitality += 100.0;
        s.vitality += 125.0;
        // unknown effect: 'decrease recharge time by 20% after swapping weapons'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Water;
#[allow(unused_variables)]
impl Effect for Water {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.healing_power += 25.0;
        m.boon_duration += 5.0;
        s.healing_power += 50.0;
        m.boon_duration += 10.0;
        s.healing_power += 100.0;
        m.boon_duration += 10.0;
        // unknown effect: 'remove a condition from you and nearby allies after using a healing skill'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Weaver;
#[allow(unused_variables)]
impl Effect for Weaver {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        m.condition_duration.burn += 10.0;
        *s += 12.0;
        //m.condition_duration.<chill> += 20.0;
        *s += 16.0;
        m.condition_duration += 10.0;
        // unknown effect: 'gain barrier after executing a <c=@abilitytype>stance</c> ability'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Wurm;
#[allow(unused_variables)]
impl Effect for Wurm {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        s.vitality += 25.0;
        s.ferocity += 35.0;
        s.vitality += 50.0;
        s.ferocity += 65.0;
        s.vitality += 100.0;
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        s.ferocity += s.vitality * 0.07;
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash, Default)]
pub struct Zephyrite;
#[allow(unused_variables)]
impl Effect for Zephyrite {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        *s += 8.0;
        *s += 10.0;
        *s += 12.0;
        *s += 14.0;
        *s += 16.0;
        // unknown effect: 'superspeed you grant lasts 33% longer'
        // unknown effect: 'using an elite skill grants you superspeed for 5 seconds'
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub enum Rune {
    Altruism(Altruism),
    Antitoxin(Antitoxin),
    Balthazar(Balthazar),
    Divinity(Divinity),
    Durability(Durability),
    Dwayna(Dwayna),
    Evasion(Evasion),
    Exuberance(Exuberance),
    Fireworks(Fireworks),
    Grenth(Grenth),
    Hoelbrak(Hoelbrak),
    Infiltration(Infiltration),
    Leadership(Leadership),
    Lyssa(Lyssa),
    Melandru(Melandru),
    Mercy(Mercy),
    NaturesBounty(NaturesBounty),
    Orr(Orr),
    Perplexity(Perplexity),
    Radiance(Radiance),
    Rage(Rage),
    RataSum(RataSum),
    Resistance(Resistance),
    Sanctuary(Sanctuary),
    Scavenging(Scavenging),
    Snowfall(Snowfall),
    Speed(Speed),
    Strength(Strength),
    Surging(Surging),
    Svanir(Svanir),
    Thorns(Thorns),
    Tormenting(Tormenting),
    Vampirism(Vampirism),
    Adventurer(Adventurer),
    Afflicted(Afflicted),
    Air(Air),
    Aristocracy(Aristocracy),
    Baelfire(Baelfire),
    Berserker(Berserker),
    Brawler(Brawler),
    Cavalier(Cavalier),
    Centaur(Centaur),
    Chronomancer(Chronomancer),
    Citadel(Citadel),
    Daredevil(Daredevil),
    Deadeye(Deadeye),
    Defender(Defender),
    Dolyak(Dolyak),
    Dragonhunter(Dragonhunter),
    Druid(Druid),
    Eagle(Eagle),
    Earth(Earth),
    Elementalist(Elementalist),
    Engineer(Engineer),
    Fire(Fire),
    Firebrand(Firebrand),
    FlameLegion(FlameLegion),
    Flock(Flock),
    Forgeman(Forgeman),
    Golemancer(Golemancer),
    Grove(Grove),
    Guardian(Guardian),
    Herald(Herald),
    Holosmith(Holosmith),
    Ice(Ice),
    Krait(Krait),
    Lich(Lich),
    MadKing(MadKing),
    Mesmer(Mesmer),
    Mirage(Mirage),
    Monk(Monk),
    Necromancer(Necromancer),
    Nightmare(Nightmare),
    Ogre(Ogre),
    Pack(Pack),
    Privateer(Privateer),
    Ranger(Ranger),
    Reaper(Reaper),
    Rebirth(Rebirth),
    Renegade(Renegade),
    Revenant(Revenant),
    Scholar(Scholar),
    Scourge(Scourge),
    Scrapper(Scrapper),
    Soulbeast(Soulbeast),
    Spellbreaker(Spellbreaker),
    Stars(Stars),
    Sunless(Sunless),
    Tempest(Tempest),
    Thief(Thief),
    Trapper(Trapper),
    Traveler(Traveler),
    Trooper(Trooper),
    Undead(Undead),
    Warrior(Warrior),
    Water(Water),
    Weaver(Weaver),
    Wurm(Wurm),
    Zephyrite(Zephyrite),
}
impl Effect for Rune {
    fn add_permanent(&self, s: &mut Stats, m: &mut Modifiers) {
        match *self {
            Rune::Altruism(x) => x.add_permanent(s, m),
            Rune::Antitoxin(x) => x.add_permanent(s, m),
            Rune::Balthazar(x) => x.add_permanent(s, m),
            Rune::Divinity(x) => x.add_permanent(s, m),
            Rune::Durability(x) => x.add_permanent(s, m),
            Rune::Dwayna(x) => x.add_permanent(s, m),
            Rune::Evasion(x) => x.add_permanent(s, m),
            Rune::Exuberance(x) => x.add_permanent(s, m),
            Rune::Fireworks(x) => x.add_permanent(s, m),
            Rune::Grenth(x) => x.add_permanent(s, m),
            Rune::Hoelbrak(x) => x.add_permanent(s, m),
            Rune::Infiltration(x) => x.add_permanent(s, m),
            Rune::Leadership(x) => x.add_permanent(s, m),
            Rune::Lyssa(x) => x.add_permanent(s, m),
            Rune::Melandru(x) => x.add_permanent(s, m),
            Rune::Mercy(x) => x.add_permanent(s, m),
            Rune::NaturesBounty(x) => x.add_permanent(s, m),
            Rune::Orr(x) => x.add_permanent(s, m),
            Rune::Perplexity(x) => x.add_permanent(s, m),
            Rune::Radiance(x) => x.add_permanent(s, m),
            Rune::Rage(x) => x.add_permanent(s, m),
            Rune::RataSum(x) => x.add_permanent(s, m),
            Rune::Resistance(x) => x.add_permanent(s, m),
            Rune::Sanctuary(x) => x.add_permanent(s, m),
            Rune::Scavenging(x) => x.add_permanent(s, m),
            Rune::Snowfall(x) => x.add_permanent(s, m),
            Rune::Speed(x) => x.add_permanent(s, m),
            Rune::Strength(x) => x.add_permanent(s, m),
            Rune::Surging(x) => x.add_permanent(s, m),
            Rune::Svanir(x) => x.add_permanent(s, m),
            Rune::Thorns(x) => x.add_permanent(s, m),
            Rune::Tormenting(x) => x.add_permanent(s, m),
            Rune::Vampirism(x) => x.add_permanent(s, m),
            Rune::Adventurer(x) => x.add_permanent(s, m),
            Rune::Afflicted(x) => x.add_permanent(s, m),
            Rune::Air(x) => x.add_permanent(s, m),
            Rune::Aristocracy(x) => x.add_permanent(s, m),
            Rune::Baelfire(x) => x.add_permanent(s, m),
            Rune::Berserker(x) => x.add_permanent(s, m),
            Rune::Brawler(x) => x.add_permanent(s, m),
            Rune::Cavalier(x) => x.add_permanent(s, m),
            Rune::Centaur(x) => x.add_permanent(s, m),
            Rune::Chronomancer(x) => x.add_permanent(s, m),
            Rune::Citadel(x) => x.add_permanent(s, m),
            Rune::Daredevil(x) => x.add_permanent(s, m),
            Rune::Deadeye(x) => x.add_permanent(s, m),
            Rune::Defender(x) => x.add_permanent(s, m),
            Rune::Dolyak(x) => x.add_permanent(s, m),
            Rune::Dragonhunter(x) => x.add_permanent(s, m),
            Rune::Druid(x) => x.add_permanent(s, m),
            Rune::Eagle(x) => x.add_permanent(s, m),
            Rune::Earth(x) => x.add_permanent(s, m),
            Rune::Elementalist(x) => x.add_permanent(s, m),
            Rune::Engineer(x) => x.add_permanent(s, m),
            Rune::Fire(x) => x.add_permanent(s, m),
            Rune::Firebrand(x) => x.add_permanent(s, m),
            Rune::FlameLegion(x) => x.add_permanent(s, m),
            Rune::Flock(x) => x.add_permanent(s, m),
            Rune::Forgeman(x) => x.add_permanent(s, m),
            Rune::Golemancer(x) => x.add_permanent(s, m),
            Rune::Grove(x) => x.add_permanent(s, m),
            Rune::Guardian(x) => x.add_permanent(s, m),
            Rune::Herald(x) => x.add_permanent(s, m),
            Rune::Holosmith(x) => x.add_permanent(s, m),
            Rune::Ice(x) => x.add_permanent(s, m),
            Rune::Krait(x) => x.add_permanent(s, m),
            Rune::Lich(x) => x.add_permanent(s, m),
            Rune::MadKing(x) => x.add_permanent(s, m),
            Rune::Mesmer(x) => x.add_permanent(s, m),
            Rune::Mirage(x) => x.add_permanent(s, m),
            Rune::Monk(x) => x.add_permanent(s, m),
            Rune::Necromancer(x) => x.add_permanent(s, m),
            Rune::Nightmare(x) => x.add_permanent(s, m),
            Rune::Ogre(x) => x.add_permanent(s, m),
            Rune::Pack(x) => x.add_permanent(s, m),
            Rune::Privateer(x) => x.add_permanent(s, m),
            Rune::Ranger(x) => x.add_permanent(s, m),
            Rune::Reaper(x) => x.add_permanent(s, m),
            Rune::Rebirth(x) => x.add_permanent(s, m),
            Rune::Renegade(x) => x.add_permanent(s, m),
            Rune::Revenant(x) => x.add_permanent(s, m),
            Rune::Scholar(x) => x.add_permanent(s, m),
            Rune::Scourge(x) => x.add_permanent(s, m),
            Rune::Scrapper(x) => x.add_permanent(s, m),
            Rune::Soulbeast(x) => x.add_permanent(s, m),
            Rune::Spellbreaker(x) => x.add_permanent(s, m),
            Rune::Stars(x) => x.add_permanent(s, m),
            Rune::Sunless(x) => x.add_permanent(s, m),
            Rune::Tempest(x) => x.add_permanent(s, m),
            Rune::Thief(x) => x.add_permanent(s, m),
            Rune::Trapper(x) => x.add_permanent(s, m),
            Rune::Traveler(x) => x.add_permanent(s, m),
            Rune::Trooper(x) => x.add_permanent(s, m),
            Rune::Undead(x) => x.add_permanent(s, m),
            Rune::Warrior(x) => x.add_permanent(s, m),
            Rune::Water(x) => x.add_permanent(s, m),
            Rune::Weaver(x) => x.add_permanent(s, m),
            Rune::Wurm(x) => x.add_permanent(s, m),
            Rune::Zephyrite(x) => x.add_permanent(s, m),
        }
    }
    fn distribute(&self, s: &mut Stats, m: &mut Modifiers) {
        match *self {
            Rune::Altruism(x) => x.distribute(s, m),
            Rune::Antitoxin(x) => x.distribute(s, m),
            Rune::Balthazar(x) => x.distribute(s, m),
            Rune::Divinity(x) => x.distribute(s, m),
            Rune::Durability(x) => x.distribute(s, m),
            Rune::Dwayna(x) => x.distribute(s, m),
            Rune::Evasion(x) => x.distribute(s, m),
            Rune::Exuberance(x) => x.distribute(s, m),
            Rune::Fireworks(x) => x.distribute(s, m),
            Rune::Grenth(x) => x.distribute(s, m),
            Rune::Hoelbrak(x) => x.distribute(s, m),
            Rune::Infiltration(x) => x.distribute(s, m),
            Rune::Leadership(x) => x.distribute(s, m),
            Rune::Lyssa(x) => x.distribute(s, m),
            Rune::Melandru(x) => x.distribute(s, m),
            Rune::Mercy(x) => x.distribute(s, m),
            Rune::NaturesBounty(x) => x.distribute(s, m),
            Rune::Orr(x) => x.distribute(s, m),
            Rune::Perplexity(x) => x.distribute(s, m),
            Rune::Radiance(x) => x.distribute(s, m),
            Rune::Rage(x) => x.distribute(s, m),
            Rune::RataSum(x) => x.distribute(s, m),
            Rune::Resistance(x) => x.distribute(s, m),
            Rune::Sanctuary(x) => x.distribute(s, m),
            Rune::Scavenging(x) => x.distribute(s, m),
            Rune::Snowfall(x) => x.distribute(s, m),
            Rune::Speed(x) => x.distribute(s, m),
            Rune::Strength(x) => x.distribute(s, m),
            Rune::Surging(x) => x.distribute(s, m),
            Rune::Svanir(x) => x.distribute(s, m),
            Rune::Thorns(x) => x.distribute(s, m),
            Rune::Tormenting(x) => x.distribute(s, m),
            Rune::Vampirism(x) => x.distribute(s, m),
            Rune::Adventurer(x) => x.distribute(s, m),
            Rune::Afflicted(x) => x.distribute(s, m),
            Rune::Air(x) => x.distribute(s, m),
            Rune::Aristocracy(x) => x.distribute(s, m),
            Rune::Baelfire(x) => x.distribute(s, m),
            Rune::Berserker(x) => x.distribute(s, m),
            Rune::Brawler(x) => x.distribute(s, m),
            Rune::Cavalier(x) => x.distribute(s, m),
            Rune::Centaur(x) => x.distribute(s, m),
            Rune::Chronomancer(x) => x.distribute(s, m),
            Rune::Citadel(x) => x.distribute(s, m),
            Rune::Daredevil(x) => x.distribute(s, m),
            Rune::Deadeye(x) => x.distribute(s, m),
            Rune::Defender(x) => x.distribute(s, m),
            Rune::Dolyak(x) => x.distribute(s, m),
            Rune::Dragonhunter(x) => x.distribute(s, m),
            Rune::Druid(x) => x.distribute(s, m),
            Rune::Eagle(x) => x.distribute(s, m),
            Rune::Earth(x) => x.distribute(s, m),
            Rune::Elementalist(x) => x.distribute(s, m),
            Rune::Engineer(x) => x.distribute(s, m),
            Rune::Fire(x) => x.distribute(s, m),
            Rune::Firebrand(x) => x.distribute(s, m),
            Rune::FlameLegion(x) => x.distribute(s, m),
            Rune::Flock(x) => x.distribute(s, m),
            Rune::Forgeman(x) => x.distribute(s, m),
            Rune::Golemancer(x) => x.distribute(s, m),
            Rune::Grove(x) => x.distribute(s, m),
            Rune::Guardian(x) => x.distribute(s, m),
            Rune::Herald(x) => x.distribute(s, m),
            Rune::Holosmith(x) => x.distribute(s, m),
            Rune::Ice(x) => x.distribute(s, m),
            Rune::Krait(x) => x.distribute(s, m),
            Rune::Lich(x) => x.distribute(s, m),
            Rune::MadKing(x) => x.distribute(s, m),
            Rune::Mesmer(x) => x.distribute(s, m),
            Rune::Mirage(x) => x.distribute(s, m),
            Rune::Monk(x) => x.distribute(s, m),
            Rune::Necromancer(x) => x.distribute(s, m),
            Rune::Nightmare(x) => x.distribute(s, m),
            Rune::Ogre(x) => x.distribute(s, m),
            Rune::Pack(x) => x.distribute(s, m),
            Rune::Privateer(x) => x.distribute(s, m),
            Rune::Ranger(x) => x.distribute(s, m),
            Rune::Reaper(x) => x.distribute(s, m),
            Rune::Rebirth(x) => x.distribute(s, m),
            Rune::Renegade(x) => x.distribute(s, m),
            Rune::Revenant(x) => x.distribute(s, m),
            Rune::Scholar(x) => x.distribute(s, m),
            Rune::Scourge(x) => x.distribute(s, m),
            Rune::Scrapper(x) => x.distribute(s, m),
            Rune::Soulbeast(x) => x.distribute(s, m),
            Rune::Spellbreaker(x) => x.distribute(s, m),
            Rune::Stars(x) => x.distribute(s, m),
            Rune::Sunless(x) => x.distribute(s, m),
            Rune::Tempest(x) => x.distribute(s, m),
            Rune::Thief(x) => x.distribute(s, m),
            Rune::Trapper(x) => x.distribute(s, m),
            Rune::Traveler(x) => x.distribute(s, m),
            Rune::Trooper(x) => x.distribute(s, m),
            Rune::Undead(x) => x.distribute(s, m),
            Rune::Warrior(x) => x.distribute(s, m),
            Rune::Water(x) => x.distribute(s, m),
            Rune::Weaver(x) => x.distribute(s, m),
            Rune::Wurm(x) => x.distribute(s, m),
            Rune::Zephyrite(x) => x.distribute(s, m),
        }
    }
    fn add_temporary(&self, s: &mut Stats, m: &mut Modifiers) {
        match *self {
            Rune::Altruism(x) => x.add_temporary(s, m),
            Rune::Antitoxin(x) => x.add_temporary(s, m),
            Rune::Balthazar(x) => x.add_temporary(s, m),
            Rune::Divinity(x) => x.add_temporary(s, m),
            Rune::Durability(x) => x.add_temporary(s, m),
            Rune::Dwayna(x) => x.add_temporary(s, m),
            Rune::Evasion(x) => x.add_temporary(s, m),
            Rune::Exuberance(x) => x.add_temporary(s, m),
            Rune::Fireworks(x) => x.add_temporary(s, m),
            Rune::Grenth(x) => x.add_temporary(s, m),
            Rune::Hoelbrak(x) => x.add_temporary(s, m),
            Rune::Infiltration(x) => x.add_temporary(s, m),
            Rune::Leadership(x) => x.add_temporary(s, m),
            Rune::Lyssa(x) => x.add_temporary(s, m),
            Rune::Melandru(x) => x.add_temporary(s, m),
            Rune::Mercy(x) => x.add_temporary(s, m),
            Rune::NaturesBounty(x) => x.add_temporary(s, m),
            Rune::Orr(x) => x.add_temporary(s, m),
            Rune::Perplexity(x) => x.add_temporary(s, m),
            Rune::Radiance(x) => x.add_temporary(s, m),
            Rune::Rage(x) => x.add_temporary(s, m),
            Rune::RataSum(x) => x.add_temporary(s, m),
            Rune::Resistance(x) => x.add_temporary(s, m),
            Rune::Sanctuary(x) => x.add_temporary(s, m),
            Rune::Scavenging(x) => x.add_temporary(s, m),
            Rune::Snowfall(x) => x.add_temporary(s, m),
            Rune::Speed(x) => x.add_temporary(s, m),
            Rune::Strength(x) => x.add_temporary(s, m),
            Rune::Surging(x) => x.add_temporary(s, m),
            Rune::Svanir(x) => x.add_temporary(s, m),
            Rune::Thorns(x) => x.add_temporary(s, m),
            Rune::Tormenting(x) => x.add_temporary(s, m),
            Rune::Vampirism(x) => x.add_temporary(s, m),
            Rune::Adventurer(x) => x.add_temporary(s, m),
            Rune::Afflicted(x) => x.add_temporary(s, m),
            Rune::Air(x) => x.add_temporary(s, m),
            Rune::Aristocracy(x) => x.add_temporary(s, m),
            Rune::Baelfire(x) => x.add_temporary(s, m),
            Rune::Berserker(x) => x.add_temporary(s, m),
            Rune::Brawler(x) => x.add_temporary(s, m),
            Rune::Cavalier(x) => x.add_temporary(s, m),
            Rune::Centaur(x) => x.add_temporary(s, m),
            Rune::Chronomancer(x) => x.add_temporary(s, m),
            Rune::Citadel(x) => x.add_temporary(s, m),
            Rune::Daredevil(x) => x.add_temporary(s, m),
            Rune::Deadeye(x) => x.add_temporary(s, m),
            Rune::Defender(x) => x.add_temporary(s, m),
            Rune::Dolyak(x) => x.add_temporary(s, m),
            Rune::Dragonhunter(x) => x.add_temporary(s, m),
            Rune::Druid(x) => x.add_temporary(s, m),
            Rune::Eagle(x) => x.add_temporary(s, m),
            Rune::Earth(x) => x.add_temporary(s, m),
            Rune::Elementalist(x) => x.add_temporary(s, m),
            Rune::Engineer(x) => x.add_temporary(s, m),
            Rune::Fire(x) => x.add_temporary(s, m),
            Rune::Firebrand(x) => x.add_temporary(s, m),
            Rune::FlameLegion(x) => x.add_temporary(s, m),
            Rune::Flock(x) => x.add_temporary(s, m),
            Rune::Forgeman(x) => x.add_temporary(s, m),
            Rune::Golemancer(x) => x.add_temporary(s, m),
            Rune::Grove(x) => x.add_temporary(s, m),
            Rune::Guardian(x) => x.add_temporary(s, m),
            Rune::Herald(x) => x.add_temporary(s, m),
            Rune::Holosmith(x) => x.add_temporary(s, m),
            Rune::Ice(x) => x.add_temporary(s, m),
            Rune::Krait(x) => x.add_temporary(s, m),
            Rune::Lich(x) => x.add_temporary(s, m),
            Rune::MadKing(x) => x.add_temporary(s, m),
            Rune::Mesmer(x) => x.add_temporary(s, m),
            Rune::Mirage(x) => x.add_temporary(s, m),
            Rune::Monk(x) => x.add_temporary(s, m),
            Rune::Necromancer(x) => x.add_temporary(s, m),
            Rune::Nightmare(x) => x.add_temporary(s, m),
            Rune::Ogre(x) => x.add_temporary(s, m),
            Rune::Pack(x) => x.add_temporary(s, m),
            Rune::Privateer(x) => x.add_temporary(s, m),
            Rune::Ranger(x) => x.add_temporary(s, m),
            Rune::Reaper(x) => x.add_temporary(s, m),
            Rune::Rebirth(x) => x.add_temporary(s, m),
            Rune::Renegade(x) => x.add_temporary(s, m),
            Rune::Revenant(x) => x.add_temporary(s, m),
            Rune::Scholar(x) => x.add_temporary(s, m),
            Rune::Scourge(x) => x.add_temporary(s, m),
            Rune::Scrapper(x) => x.add_temporary(s, m),
            Rune::Soulbeast(x) => x.add_temporary(s, m),
            Rune::Spellbreaker(x) => x.add_temporary(s, m),
            Rune::Stars(x) => x.add_temporary(s, m),
            Rune::Sunless(x) => x.add_temporary(s, m),
            Rune::Tempest(x) => x.add_temporary(s, m),
            Rune::Thief(x) => x.add_temporary(s, m),
            Rune::Trapper(x) => x.add_temporary(s, m),
            Rune::Traveler(x) => x.add_temporary(s, m),
            Rune::Trooper(x) => x.add_temporary(s, m),
            Rune::Undead(x) => x.add_temporary(s, m),
            Rune::Warrior(x) => x.add_temporary(s, m),
            Rune::Water(x) => x.add_temporary(s, m),
            Rune::Weaver(x) => x.add_temporary(s, m),
            Rune::Wurm(x) => x.add_temporary(s, m),
            Rune::Zephyrite(x) => x.add_temporary(s, m),
        }
    }
}
impl Rune {
    pub const COUNT: usize = 99;
    pub fn from_index(i: usize) -> Rune {
        match i {
            0 => Rune::Altruism(Altruism),
            1 => Rune::Antitoxin(Antitoxin),
            2 => Rune::Balthazar(Balthazar),
            3 => Rune::Divinity(Divinity),
            4 => Rune::Durability(Durability),
            5 => Rune::Dwayna(Dwayna),
            6 => Rune::Evasion(Evasion),
            7 => Rune::Exuberance(Exuberance),
            8 => Rune::Fireworks(Fireworks),
            9 => Rune::Grenth(Grenth),
            10 => Rune::Hoelbrak(Hoelbrak),
            11 => Rune::Infiltration(Infiltration),
            12 => Rune::Leadership(Leadership),
            13 => Rune::Lyssa(Lyssa),
            14 => Rune::Melandru(Melandru),
            15 => Rune::Mercy(Mercy),
            16 => Rune::NaturesBounty(NaturesBounty),
            17 => Rune::Orr(Orr),
            18 => Rune::Perplexity(Perplexity),
            19 => Rune::Radiance(Radiance),
            20 => Rune::Rage(Rage),
            21 => Rune::RataSum(RataSum),
            22 => Rune::Resistance(Resistance),
            23 => Rune::Sanctuary(Sanctuary),
            24 => Rune::Scavenging(Scavenging),
            25 => Rune::Snowfall(Snowfall),
            26 => Rune::Speed(Speed),
            27 => Rune::Strength(Strength),
            28 => Rune::Surging(Surging),
            29 => Rune::Svanir(Svanir),
            30 => Rune::Thorns(Thorns),
            31 => Rune::Tormenting(Tormenting),
            32 => Rune::Vampirism(Vampirism),
            33 => Rune::Adventurer(Adventurer),
            34 => Rune::Afflicted(Afflicted),
            35 => Rune::Air(Air),
            36 => Rune::Aristocracy(Aristocracy),
            37 => Rune::Baelfire(Baelfire),
            38 => Rune::Berserker(Berserker),
            39 => Rune::Brawler(Brawler),
            40 => Rune::Cavalier(Cavalier),
            41 => Rune::Centaur(Centaur),
            42 => Rune::Chronomancer(Chronomancer),
            43 => Rune::Citadel(Citadel),
            44 => Rune::Daredevil(Daredevil),
            45 => Rune::Deadeye(Deadeye),
            46 => Rune::Defender(Defender),
            47 => Rune::Dolyak(Dolyak),
            48 => Rune::Dragonhunter(Dragonhunter),
            49 => Rune::Druid(Druid),
            50 => Rune::Eagle(Eagle),
            51 => Rune::Earth(Earth),
            52 => Rune::Elementalist(Elementalist),
            53 => Rune::Engineer(Engineer),
            54 => Rune::Fire(Fire),
            55 => Rune::Firebrand(Firebrand),
            56 => Rune::FlameLegion(FlameLegion),
            57 => Rune::Flock(Flock),
            58 => Rune::Forgeman(Forgeman),
            59 => Rune::Golemancer(Golemancer),
            60 => Rune::Grove(Grove),
            61 => Rune::Guardian(Guardian),
            62 => Rune::Herald(Herald),
            63 => Rune::Holosmith(Holosmith),
            64 => Rune::Ice(Ice),
            65 => Rune::Krait(Krait),
            66 => Rune::Lich(Lich),
            67 => Rune::MadKing(MadKing),
            68 => Rune::Mesmer(Mesmer),
            69 => Rune::Mirage(Mirage),
            70 => Rune::Monk(Monk),
            71 => Rune::Necromancer(Necromancer),
            72 => Rune::Nightmare(Nightmare),
            73 => Rune::Ogre(Ogre),
            74 => Rune::Pack(Pack),
            75 => Rune::Privateer(Privateer),
            76 => Rune::Ranger(Ranger),
            77 => Rune::Reaper(Reaper),
            78 => Rune::Rebirth(Rebirth),
            79 => Rune::Renegade(Renegade),
            80 => Rune::Revenant(Revenant),
            81 => Rune::Scholar(Scholar),
            82 => Rune::Scourge(Scourge),
            83 => Rune::Scrapper(Scrapper),
            84 => Rune::Soulbeast(Soulbeast),
            85 => Rune::Spellbreaker(Spellbreaker),
            86 => Rune::Stars(Stars),
            87 => Rune::Sunless(Sunless),
            88 => Rune::Tempest(Tempest),
            89 => Rune::Thief(Thief),
            90 => Rune::Trapper(Trapper),
            91 => Rune::Traveler(Traveler),
            92 => Rune::Trooper(Trooper),
            93 => Rune::Undead(Undead),
            94 => Rune::Warrior(Warrior),
            95 => Rune::Water(Water),
            96 => Rune::Weaver(Weaver),
            97 => Rune::Wurm(Wurm),
            98 => Rune::Zephyrite(Zephyrite),
            _ => panic!("index {} out of range for Rune", i),
        }
    }
    pub fn iter() -> impl Iterator<Item = Rune> {
        (0 .. Rune::COUNT).map(Rune::from_index)
    }
}
impl From<Altruism> for Rune {
    fn from(x: Altruism) -> Rune { Rune::Altruism(x) }
}
impl From<Antitoxin> for Rune {
    fn from(x: Antitoxin) -> Rune { Rune::Antitoxin(x) }
}
impl From<Balthazar> for Rune {
    fn from(x: Balthazar) -> Rune { Rune::Balthazar(x) }
}
impl From<Divinity> for Rune {
    fn from(x: Divinity) -> Rune { Rune::Divinity(x) }
}
impl From<Durability> for Rune {
    fn from(x: Durability) -> Rune { Rune::Durability(x) }
}
impl From<Dwayna> for Rune {
    fn from(x: Dwayna) -> Rune { Rune::Dwayna(x) }
}
impl From<Evasion> for Rune {
    fn from(x: Evasion) -> Rune { Rune::Evasion(x) }
}
impl From<Exuberance> for Rune {
    fn from(x: Exuberance) -> Rune { Rune::Exuberance(x) }
}
impl From<Fireworks> for Rune {
    fn from(x: Fireworks) -> Rune { Rune::Fireworks(x) }
}
impl From<Grenth> for Rune {
    fn from(x: Grenth) -> Rune { Rune::Grenth(x) }
}
impl From<Hoelbrak> for Rune {
    fn from(x: Hoelbrak) -> Rune { Rune::Hoelbrak(x) }
}
impl From<Infiltration> for Rune {
    fn from(x: Infiltration) -> Rune { Rune::Infiltration(x) }
}
impl From<Leadership> for Rune {
    fn from(x: Leadership) -> Rune { Rune::Leadership(x) }
}
impl From<Lyssa> for Rune {
    fn from(x: Lyssa) -> Rune { Rune::Lyssa(x) }
}
impl From<Melandru> for Rune {
    fn from(x: Melandru) -> Rune { Rune::Melandru(x) }
}
impl From<Mercy> for Rune {
    fn from(x: Mercy) -> Rune { Rune::Mercy(x) }
}
impl From<NaturesBounty> for Rune {
    fn from(x: NaturesBounty) -> Rune { Rune::NaturesBounty(x) }
}
impl From<Orr> for Rune {
    fn from(x: Orr) -> Rune { Rune::Orr(x) }
}
impl From<Perplexity> for Rune {
    fn from(x: Perplexity) -> Rune { Rune::Perplexity(x) }
}
impl From<Radiance> for Rune {
    fn from(x: Radiance) -> Rune { Rune::Radiance(x) }
}
impl From<Rage> for Rune {
    fn from(x: Rage) -> Rune { Rune::Rage(x) }
}
impl From<RataSum> for Rune {
    fn from(x: RataSum) -> Rune { Rune::RataSum(x) }
}
impl From<Resistance> for Rune {
    fn from(x: Resistance) -> Rune { Rune::Resistance(x) }
}
impl From<Sanctuary> for Rune {
    fn from(x: Sanctuary) -> Rune { Rune::Sanctuary(x) }
}
impl From<Scavenging> for Rune {
    fn from(x: Scavenging) -> Rune { Rune::Scavenging(x) }
}
impl From<Snowfall> for Rune {
    fn from(x: Snowfall) -> Rune { Rune::Snowfall(x) }
}
impl From<Speed> for Rune {
    fn from(x: Speed) -> Rune { Rune::Speed(x) }
}
impl From<Strength> for Rune {
    fn from(x: Strength) -> Rune { Rune::Strength(x) }
}
impl From<Surging> for Rune {
    fn from(x: Surging) -> Rune { Rune::Surging(x) }
}
impl From<Svanir> for Rune {
    fn from(x: Svanir) -> Rune { Rune::Svanir(x) }
}
impl From<Thorns> for Rune {
    fn from(x: Thorns) -> Rune { Rune::Thorns(x) }
}
impl From<Tormenting> for Rune {
    fn from(x: Tormenting) -> Rune { Rune::Tormenting(x) }
}
impl From<Vampirism> for Rune {
    fn from(x: Vampirism) -> Rune { Rune::Vampirism(x) }
}
impl From<Adventurer> for Rune {
    fn from(x: Adventurer) -> Rune { Rune::Adventurer(x) }
}
impl From<Afflicted> for Rune {
    fn from(x: Afflicted) -> Rune { Rune::Afflicted(x) }
}
impl From<Air> for Rune {
    fn from(x: Air) -> Rune { Rune::Air(x) }
}
impl From<Aristocracy> for Rune {
    fn from(x: Aristocracy) -> Rune { Rune::Aristocracy(x) }
}
impl From<Baelfire> for Rune {
    fn from(x: Baelfire) -> Rune { Rune::Baelfire(x) }
}
impl From<Berserker> for Rune {
    fn from(x: Berserker) -> Rune { Rune::Berserker(x) }
}
impl From<Brawler> for Rune {
    fn from(x: Brawler) -> Rune { Rune::Brawler(x) }
}
impl From<Cavalier> for Rune {
    fn from(x: Cavalier) -> Rune { Rune::Cavalier(x) }
}
impl From<Centaur> for Rune {
    fn from(x: Centaur) -> Rune { Rune::Centaur(x) }
}
impl From<Chronomancer> for Rune {
    fn from(x: Chronomancer) -> Rune { Rune::Chronomancer(x) }
}
impl From<Citadel> for Rune {
    fn from(x: Citadel) -> Rune { Rune::Citadel(x) }
}
impl From<Daredevil> for Rune {
    fn from(x: Daredevil) -> Rune { Rune::Daredevil(x) }
}
impl From<Deadeye> for Rune {
    fn from(x: Deadeye) -> Rune { Rune::Deadeye(x) }
}
impl From<Defender> for Rune {
    fn from(x: Defender) -> Rune { Rune::Defender(x) }
}
impl From<Dolyak> for Rune {
    fn from(x: Dolyak) -> Rune { Rune::Dolyak(x) }
}
impl From<Dragonhunter> for Rune {
    fn from(x: Dragonhunter) -> Rune { Rune::Dragonhunter(x) }
}
impl From<Druid> for Rune {
    fn from(x: Druid) -> Rune { Rune::Druid(x) }
}
impl From<Eagle> for Rune {
    fn from(x: Eagle) -> Rune { Rune::Eagle(x) }
}
impl From<Earth> for Rune {
    fn from(x: Earth) -> Rune { Rune::Earth(x) }
}
impl From<Elementalist> for Rune {
    fn from(x: Elementalist) -> Rune { Rune::Elementalist(x) }
}
impl From<Engineer> for Rune {
    fn from(x: Engineer) -> Rune { Rune::Engineer(x) }
}
impl From<Fire> for Rune {
    fn from(x: Fire) -> Rune { Rune::Fire(x) }
}
impl From<Firebrand> for Rune {
    fn from(x: Firebrand) -> Rune { Rune::Firebrand(x) }
}
impl From<FlameLegion> for Rune {
    fn from(x: FlameLegion) -> Rune { Rune::FlameLegion(x) }
}
impl From<Flock> for Rune {
    fn from(x: Flock) -> Rune { Rune::Flock(x) }
}
impl From<Forgeman> for Rune {
    fn from(x: Forgeman) -> Rune { Rune::Forgeman(x) }
}
impl From<Golemancer> for Rune {
    fn from(x: Golemancer) -> Rune { Rune::Golemancer(x) }
}
impl From<Grove> for Rune {
    fn from(x: Grove) -> Rune { Rune::Grove(x) }
}
impl From<Guardian> for Rune {
    fn from(x: Guardian) -> Rune { Rune::Guardian(x) }
}
impl From<Herald> for Rune {
    fn from(x: Herald) -> Rune { Rune::Herald(x) }
}
impl From<Holosmith> for Rune {
    fn from(x: Holosmith) -> Rune { Rune::Holosmith(x) }
}
impl From<Ice> for Rune {
    fn from(x: Ice) -> Rune { Rune::Ice(x) }
}
impl From<Krait> for Rune {
    fn from(x: Krait) -> Rune { Rune::Krait(x) }
}
impl From<Lich> for Rune {
    fn from(x: Lich) -> Rune { Rune::Lich(x) }
}
impl From<MadKing> for Rune {
    fn from(x: MadKing) -> Rune { Rune::MadKing(x) }
}
impl From<Mesmer> for Rune {
    fn from(x: Mesmer) -> Rune { Rune::Mesmer(x) }
}
impl From<Mirage> for Rune {
    fn from(x: Mirage) -> Rune { Rune::Mirage(x) }
}
impl From<Monk> for Rune {
    fn from(x: Monk) -> Rune { Rune::Monk(x) }
}
impl From<Necromancer> for Rune {
    fn from(x: Necromancer) -> Rune { Rune::Necromancer(x) }
}
impl From<Nightmare> for Rune {
    fn from(x: Nightmare) -> Rune { Rune::Nightmare(x) }
}
impl From<Ogre> for Rune {
    fn from(x: Ogre) -> Rune { Rune::Ogre(x) }
}
impl From<Pack> for Rune {
    fn from(x: Pack) -> Rune { Rune::Pack(x) }
}
impl From<Privateer> for Rune {
    fn from(x: Privateer) -> Rune { Rune::Privateer(x) }
}
impl From<Ranger> for Rune {
    fn from(x: Ranger) -> Rune { Rune::Ranger(x) }
}
impl From<Reaper> for Rune {
    fn from(x: Reaper) -> Rune { Rune::Reaper(x) }
}
impl From<Rebirth> for Rune {
    fn from(x: Rebirth) -> Rune { Rune::Rebirth(x) }
}
impl From<Renegade> for Rune {
    fn from(x: Renegade) -> Rune { Rune::Renegade(x) }
}
impl From<Revenant> for Rune {
    fn from(x: Revenant) -> Rune { Rune::Revenant(x) }
}
impl From<Scholar> for Rune {
    fn from(x: Scholar) -> Rune { Rune::Scholar(x) }
}
impl From<Scourge> for Rune {
    fn from(x: Scourge) -> Rune { Rune::Scourge(x) }
}
impl From<Scrapper> for Rune {
    fn from(x: Scrapper) -> Rune { Rune::Scrapper(x) }
}
impl From<Soulbeast> for Rune {
    fn from(x: Soulbeast) -> Rune { Rune::Soulbeast(x) }
}
impl From<Spellbreaker> for Rune {
    fn from(x: Spellbreaker) -> Rune { Rune::Spellbreaker(x) }
}
impl From<Stars> for Rune {
    fn from(x: Stars) -> Rune { Rune::Stars(x) }
}
impl From<Sunless> for Rune {
    fn from(x: Sunless) -> Rune { Rune::Sunless(x) }
}
impl From<Tempest> for Rune {
    fn from(x: Tempest) -> Rune { Rune::Tempest(x) }
}
impl From<Thief> for Rune {
    fn from(x: Thief) -> Rune { Rune::Thief(x) }
}
impl From<Trapper> for Rune {
    fn from(x: Trapper) -> Rune { Rune::Trapper(x) }
}
impl From<Traveler> for Rune {
    fn from(x: Traveler) -> Rune { Rune::Traveler(x) }
}
impl From<Trooper> for Rune {
    fn from(x: Trooper) -> Rune { Rune::Trooper(x) }
}
impl From<Undead> for Rune {
    fn from(x: Undead) -> Rune { Rune::Undead(x) }
}
impl From<Warrior> for Rune {
    fn from(x: Warrior) -> Rune { Rune::Warrior(x) }
}
impl From<Water> for Rune {
    fn from(x: Water) -> Rune { Rune::Water(x) }
}
impl From<Weaver> for Rune {
    fn from(x: Weaver) -> Rune { Rune::Weaver(x) }
}
impl From<Wurm> for Rune {
    fn from(x: Wurm) -> Rune { Rune::Wurm(x) }
}
impl From<Zephyrite> for Rune {
    fn from(x: Zephyrite) -> Rune { Rune::Zephyrite(x) }
}

// END GENERATED CODE
